/**
 * Emits the seed SQL for dc_card_schemas and dc_agents straight from the
 * transcribed TypeScript sources, so the database copy cannot drift from the
 * documents. Run with: npm run seed:sql
 */
import { cardOrder } from '../src/schemas'
import { agentInstructions, protocolText } from '../src/agents/instructions'

/** Dollar-quote with a tag that cannot appear in the payload. */
function q(s: string): string {
  let tag = 'seed'
  let i = 0
  while (s.includes(`$${tag}$`)) tag = `seed${++i}`
  return `$${tag}$${s}$${tag}$`
}

const out: string[] = []
out.push('-- Generated by scripts/seed-sql.ts — do not edit by hand.')
out.push('begin;')

// Card field schemas stay in TypeScript: they are the fixed spec transcribed
// from the master prompt templates, and the frontend needs them typed. Only the
// agent instructions live in the database, because those are what the
// improvement-proposal loop is meant to evolve.

// Built-in agent configs (owner is null). Re-seeding replaces the built-in row
// rather than bumping the version — versions are for user-approved evolution.
out.push(`\ndelete from public.dc_agents where owner is null;`)
for (const type of cardOrder) {
  const inst = agentInstructions[type]
  out.push(`
insert into public.dc_agents (owner, agent, version, active, role, knowledge, protocol, note)
values (null, '${type}', 1, true, ${q(inst.role)}, ${q(inst.knowledge)}, ${q(protocolText(type))},
        ${q('Kaynak dokümanlardan aktarılan ilk sürüm.')});`)
}

out.push('commit;')
console.log(out.join('\n'))
